---
- name: Deploy Tomcat Container
  hosts: localhost
  tasks:
    - name: create container
      docker_container:
        name: myweb-tomcat
        image: tomcat:hello
        state: started
        ports: 
          - "80:8080"
...
